### ISSUE TITLE
add font referenced in css

### ISSUE THREAD

**Issue by javatlacati** [javatlacati/regextester#1]
Only happens on netbeans plugin.

```
java.io.IOException: Could not connect to URL nbresloc:/org/javapro/regextester/fonts/Fixedsys500c.svg. No such resource was found.
	at org.netbeans.core.startup.NbResourceStreamHandler$Connection.connect(NbResourceStreamHandler.java:143)
	at com.sun.webkit.network.URLLoader.sendRequest(URLLoader.java:371)
[catch] at com.sun.webkit.network.URLLoader.doRun(URLLoader.java:167)
	at com.sun.webkit.network.URLLoader.lambda$run$99(URLLoader.java:132)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.webkit.network.URLLoader.run(URLLoader.java:131)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by dukescript** [comment]
Could you add steps how to reproduce it? I'll try to fix it then.
